version: 1.0.{build}
image: Visual Studio 2019
before_build:
- cmd: echo -%APPVEYOR_BUILD_NUMBER% >> VERSION.txt
# - cmd: cd samples/HelloWorldApp
- cmd: dotnet restore WebWindow.Samples.sln
- cmd: nuget restore WebWindow.Samples.sln
build:
  project: WebWindow.Samples.sln
  verbosity: minimal
configuration:
  - Release
after_build:
- cmd: dir
# - cmd: cd samples/HelloWorldApp
- cmd: dotnet build -f netcoreapp3.0 WebWindow.Samples.sln
- 7z a archive.7z "C:\projects\webwindow\samples"
- ps: appveyor PushArtifact archive.7z

